#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:
    taskapp:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: taskapp
        ports:
            - 3333:3000
